/*

 /HOME/BAD/GBSNAKE/RES/SNAKE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef ___home_bad_gbsnake_res_snake_h_INCLUDE
#define ___home_bad_gbsnake_res_snake_h_INCLUDE

/* Bank of tiles. */
#define SnakeBank 0
/* Start of tile array. */
extern const unsigned char Snake[];

#endif

/* End of /HOME/BAD/GBSNAKE/RES/SNAKE.H */
